from fastapi import APIRouter, Depends
from app.api.deps import get_current_user
from app.models.user import User

router = APIRouter(prefix="/api/ai", tags=["ai"])


@router.post("/chat")
def chat(payload: dict, _: User = Depends(get_current_user)):
    prompt = payload.get("message", "")
    return {"success": True, "response": f"AI stub response for: {prompt}"}


@router.post("/generate-questions")
def generate_questions(payload: dict, _: User = Depends(get_current_user)):
    role = payload.get("jobTitle", "General")
    return {"success": True, "questions": [f"Tell me about your {role} experience.", "Describe a challenging project you shipped."]}


@router.post("/transcribe-audio")
def transcribe(_: User = Depends(get_current_user)):
    return {"success": True, "transcript": "Demo transcript generated by Python backend."}


@router.post("/evaluate-answer")
def evaluate_answer(payload: dict, _: User = Depends(get_current_user)):
    return {"success": True, "score": 8.2, "feedback": f"Evaluation complete for answer: {payload.get('answer', '')[:80]}"}


@router.post("/evaluate-session")
def evaluate_session(_: User = Depends(get_current_user)):
    return {"success": True, "overallScore": 8.4, "overallFeedback": "Good session performance."}
